training_config:
  model_checkpoint: "ElnaggarLab/ankh-base"
  epochs: 10
  lr: 2e-4
  seed: 42
  factor: 0.1
  patience: 4
  min_lr: 1e-8
  batch_size: 4
  num_workers: 3
  optimizer: adamw
  weight_decay: 1e-2
