model_config:
  input_dim: 1536
  nhead: 4
  hidden_dim: 1536
  num_hidden_layers: 1
  num_layers: 1
  kernel_size: 7
  dropout: 0.2
  pooling: max


training_config:
  epochs: 10
  lr: 2e-4
  seed: 42
  factor: 0.5
  patience: 3
  min_lr: 1e-8
  batch_size: 1
  num_workers: 1
  optimizer: adamw
  weight_decay: 4e-2
