model_config:
  input_dim: 1536
  nhead: 4
  hidden_dim: 728
  num_hidden_layers: 2
  num_layers: 2
  kernel_size: 7
  dropout: 0.2
  pooling: max


training_config:
  epochs: 20
  lr: 2e-4
  seed: 42
  factor: 0.1
  patience: 4
  min_lr: 1e-8
  batch_size: 64
  num_workers: 4
  optimizer: adamw
  weight_decay: 1e-2
